package org.dbpedia.spotlight.db

import org.apache.hadoop.conf.Configuration
import org.apache.hadoop.fs.FileSystem
import org.apache.hadoop.fs.Path
import org.apache.hadoop.io.IntWritable
import org.apache.hadoop.io.LongWritable
import org.apache.hadoop.io.SequenceFile
import org.apache.hadoop.io.Text

/**
 * @author Chris Hokamp
 *         - import a sequence file generated by mahout
 */
object ImportSequenceFile {

  //def readVectors (File matrixFiles):

}
